### ISSUE TITLE
Why do you translate the word "var" to "let"?

### ISSUE THREAD

**Issue by aykutkardas** [tayfunerbilen/jquery-to-javascript-convert#2]
The `var` syntax is not linked to jquery.
In addition, the word `let` is partially supported by + IE11.

Check browser support:
https://caniuse.com/#search=let

https://github.com/tayfunerbilen/jquery-to-javascript-convert/blob/92ed98621e86824d2a1fbdba383d1979afe0f847/src/jquerytojs.php#L200

**Comment by tayfunerbilen** [comment]
it's up to you, you can remove the method if you don't wanna use :) I usually using let, that's why I decided to change "var" keywords to "let".

**Comment by Fabsolute** [comment]
this function does not effect only `var` keyword. For instance when trying to use like this `var variable = 3;` then output is `let letiable = 3;`

**Comment by tayfunerbilen** [comment]
> this function does not effect only `var` keyword. For instance when trying to use like this `var variable = 3;` then output is `let letiable = 3;`

thanks for feedback. I fixed the problem and made optional.
