### ISSUE TITLE
The pattern used to convert $ .each does not work correctly.

### ISSUE THREAD

**Issue by aykutkardas** [tayfunerbilen/jquery-to-javascript-convert#7]
The pattern here doesn't work properly. If spaces are used in parts where there are spaces, the match will be incorrect.

[RegExr Demo](https://regexr.com/4ta0c)

**Good**
```js
$.each(list, function(key, val){
	console.log($(val).html());
});
```

**No Match**
```js
$.each(list, function (key, val){
	console.log($(val).html());
});
```

**No Match**
```js
$.each(list, function(key, val) {
	console.log($(val).html());
});
```

https://github.com/tayfunerbilen/jquery-to-javascript-convert/blob/a0b5f80d91b8122ecfdc2dbda96636130a5e65a3/src/Traits/DOM.php#L184

**Comment by tayfunerbilen** [comment]
Thanks, I changed the pattern. It will be work correctly now.
