### ISSUE TITLE
Neden php 

### ISSUE THREAD

**Issue by hacicavcav** [tayfunerbilen/jquery-to-javascript-convert#8]
Proje güzel fakat php ile olması beni şaşırttı jquery'i native javascripte çevirmek için php'nin araya dahil edilmesini beklemiyordum doğrusu :). Javascript kütüphanesi olarak yazılsaydı bence çok daha pratik olurdu.

**Comment by tayfunerbilen** [comment]
Javascript versiyonu için şu repo'ya bakabilirsiniz: https://github.com/aykutkardas/jquery-to-javascript
